name: Verificação Agendada

# Controla quando a ação deve rodar.
on:
  schedule:
    - cron: "1 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Verifica todos os domínios
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
